version: "3.9"
services:
  rag-web:
    build: ../../apps/rag-web
    ports:
      - "5173:80"
    depends_on: [rag-api]
    

  rag-api:
    build:
      context: ../../apps/rag-api
      dockerfile: Dockerfile
    env_file:
      - ../../apps/rag-api/.env
    ports:
      - "8000:8000"
    depends_on: [qdrant, redis, minio]
    volumes:
      - ../../data/app:/app/data


  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333", "6334:6334"]
    volumes:
      - ../../data/qdrant:/qdrant/storage


  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]


  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - ../../data/minio:/data


  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686" # UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP